.TH EUKTOPDF 1 2010/01/08 Eukleides "Eukleides Manual"
.SH NAME
euktopdf - Eukleides to PDF converter
.SH SYNOPSIS
\fBeuktopdf\fP \fIFILE\fP
.SH DESCRIPTION
Eukleides is a computer language devoted to elementary plane geometry.
It aims to be a fairly comprehensive system to create geometric figures,
either static or dynamic.
It allows to handle geometric types of data like points, vectors,
lines, circles, or conics.
.PP
The \fBeuktopdf\fP script is useful to convert auxiliary Eukleides
files, generated when running
.BR pdflatex (1)
on a LaTeX document containing Eukleides figures, into
auxiliary PDF files.
The argument for the script is the LaTeX source name.
.SH AUTHOR
Christian Obrecht <obrecht \fIat\fP eukleides \fIdot\fP org>.
.SH "SEE ALSO"
Eukleides info pages for full documentation.
.br
.BR eukleides (1),
.BR euktopst (1),
.BR euktoeps (1),
.BR euktotex (1).
