.TH EUKTOTEX 1 2010/01/08 Eukleides "Eukleides Manual"
.SH NAME
euktotex - Eukleides to PSTricks converter
.SH SYNOPSIS
\fBeuktotex\fP \fIFILE\fP
.SH DESCRIPTION
Eukleides is a computer language devoted to elementary plane geometry.
It aims to be a fairly comprehensive system to create geometric figures,
either static or dynamic.
It allows to handle geometric types of data like points, vectors,
lines, circles, or conics.
.PP
The \fBeuktotex\fP script is useful to convert auxiliary Eukleides
files, generated when running
.BR latex (1)
on a LaTeX document containing Eukleides figures, into
auxiliary TeX files.
The argument for the script is the LaTeX source name.
.SH AUTHOR
Christian Obrecht <obrecht \fIat\fP eukleides \fIdot\fP org>.
.SH "SEE ALSO"
Eukleides info pages for full documentation.
.br
.BR eukleides (1),
.BR euktopst (1),
.BR euktoeps (1),
.BR euktopdf (1).
