#!/bin/bash
#
#  Eukleides version 1.5.4
#  Copyright (c) Christian Obrecht 2004-2010
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#

if [ ! $1 ]
then
    echo "Missing file name. Exiting." > /dev/stderr
    exit 1
fi

src=$(expr $1 : '\(.*\)\.[^.]*' '|' $1)

for f in $src-fig*.euk
do
  if [ ! -e $f ]
  then
    echo "No figure files for '$1'. Exiting." > /dev/stderr
    exit 1
  fi
  base=$(expr $f : '\(.*\)\.euk')
  tex=$base.tex
  echo "\\documentclass{article}" > $tex &&
  if [ -e $src.pac ]
  then
    cat $src.pac >> $tex
  fi &&
  echo "\\usepackage{pstricks,pst-eps}" >> $tex &&
  echo "\\nofiles" >> $tex &&
  echo "\\pagestyle{empty}" >> $tex &&
  echo "\\begin{document}" >> $tex &&
  echo "\\TeXtoEPS" >> $tex &&
  euktopst -b -o $f >> $tex &&
  echo "\\endTeXtoEPS" >> $tex &&
  echo "\\end{document}" >> $tex &&
  latex -interaction=nonstopmode $tex > /dev/null
  if [ $? -ne 0 ]
  then
    echo "LaTeX error: please check '$base.log'." > /dev/stderr
    exit 1
  fi
  dvips -q -E -o $base.eps $base.dvi &&
  epstopdf $base.eps &&
  rm -f $base.{tex,log,dvi,eps}
done
